# Generated by Django 5.1.4 on 2025-01-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='country',
            field=models.CharField(default='D.R.Congo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='name',
            field=models.CharField(default='congo airways', max_length=100),
            preserve_default=False,
        ),
    ]
