# Generated by Django 5.1.4 on 2025-01-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0002_airline_country_airline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=10),
        ),
    ]
