# Generated by Django 5.1.4 on 2025-01-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0004_reservation_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
